apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: go-to-production
  description: A reference implementation for modern cloud-native practices on Google Cloud Platform (GCP).
  tags:
    - go
    - gke
    - cloud-native
    - reference-architecture
  links:
    - title: Source Code
      url: https://github.com/stevemcghee/go-to-production
    - title: Documentation
      url: https://github.com/stevemcghee/go-to-production/tree/main/docs
spec:
  type: service
  lifecycle: production
  owner: platform-engineering
  system: reference-architectures
