apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: todo-app-pipeline
description: Canary deployment pipeline for todo-app-go
serialPipeline:
  stages:
  - targetId: production
    profiles: ["verify"]
    strategy:
              canary:
                verify: true        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: todo-app-go-service
              deployment: todo-app-go
        canaryDeployment:
          percentages: [1, 10]
          postdeploy:
            actions: ["verify"]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: production
description: Production GKE cluster
gke:
  cluster: projects/smcghee-todo-p15n-38a6/locations/us-central1/clusters/todo-app-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Automation
metadata:
  name: todo-app-automation
  description: Automate canary advancement
serviceAccount: github-actions-deployer@smcghee-todo-p15n-38a6.iam.gserviceaccount.com
selector:
  targets:
  - id: production
rules:
- advanceRolloutRule:
    id: advance-rollout
    sourcePhases: ["canary-1", "canary-10"]
    wait: 2m  # Wait 2 minutes for metrics to stabilize before verification
