apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: todo-app-ingress-global
  namespace: todo-app
  annotations:
    networking.gke.io/static-ip: "MCI_IP"
    networking.gke.io/pre-shared-certs: "MANAGED_CERT_NAME"
spec:
  template:
    spec:
      backend:
        serviceName: todo-app-mcs
        servicePort: 80
