apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: todo-app-ingress-global
  namespace: todo-app
  annotations:
    networking.gke.io/static-ip: "todo-app-ip"
    networking.gke.io/pre-shared-certs: "todo-app-cert"
spec:
  template:
    spec:
      backend:
        serviceName: todo-app-mcs
        servicePort: 80
